import { NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import { generateDailyLesson } from '@/lib/ai/content-generator'
import { getLearningProgress } from '@/lib/ai/progress-tracker'
import { getCurriculum, type LevelId } from '@/lib/curriculum'

export async function POST(request: Request) {
  try {
    const supabase = await createClient()
    const { data: { user } } = await supabase.auth.getUser()

    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const { data: profile } = await supabase
      .from('profiles')
      .select('current_level, target_level, daily_minutes, locale, study_intensity')
      .eq('id', user.id)
      .single()

    if (!profile?.current_level) {
      return NextResponse.json({ error: 'Complete onboarding first' }, { status: 400 })
    }

    const url = new URL(request.url)
    const forceRegenerate = url.searchParams.get('force') === 'true'

    // Check if today's lesson already exists → return cached unless force=true
    const today = new Date().toISOString().split('T')[0]
    const { data: existingTasks } = await supabase
      .from('daily_tasks')
      .select('id, task_type, content, duration_minutes')
      .eq('user_id', user.id)
      .eq('date', today)

    if (existingTasks && existingTasks.length > 0) {
      if (forceRegenerate) {
        // Delete old cache to start fresh
        await supabase.from('daily_tasks').delete().eq('user_id', user.id).eq('date', today)
      } else {
        return NextResponse.json({
          lesson: {
            unitId: 'cached',
            unitTitle: '',
            estimatedMinutes: profile.daily_minutes || 30,
            tasks: existingTasks.map((t: any) => ({
              type: t.task_type,
              title: t.task_type.charAt(0).toUpperCase() + t.task_type.slice(1),
              durationMinutes: t.duration_minutes,
              content: t.content,
            })),
          },
          cached: true,
        })
      }
    }

    // ============================================
    // SMART LESSON GENERATION
    // Analyze progress → pick right unit → vary focus
    // ============================================

    // 1. Get learning progress (analyzes all past daily_tasks)
    const progress = await getLearningProgress(user.id)

    // 2. Determine today's focus based on:
    //    - Day of week (variety)
    //    - Unit progress (new grammar or more vocab?)
    //    - Weak areas (need review?)
    const dayOfWeek = new Date().getDay()

    let focusAreas: ('vocabulary' | 'grammar' | 'reading' | 'writing' | 'review')[] = []
    
    // We get how many lessons they've done in this unit
    const lessonsInUnit = progress.unitProgress.totalLessons

    // Always include review if we have due SRS cards or weak areas
    if (progress.dueReviews.length > 0 || progress.weakAreas.length > 0 || lessonsInUnit > 0) {
      focusAreas.push('review')
    }
    
    // Always include vocabulary and grammar from Day 1 to avoid giving the impression that the app "only has vocabulary"
    focusAreas.push('vocabulary', 'grammar')
    
    // Day 2 (lesson 1) introduces reading
    if (lessonsInUnit >= 1 || profile.daily_minutes >= 30) focusAreas.push('reading')
    
    // Day 3 (lesson 2) introduces writing
    if (lessonsInUnit >= 2 || profile.daily_minutes >= 60) focusAreas.push('writing')

    // 3. Generate the daily lesson using AI
    const lesson = await generateDailyLesson(
      progress.currentUnit,
      focusAreas,
      profile.daily_minutes || 30,
      profile.locale || 'en',
      progress.previousVocab,
      progress.dueReviews,
      profile.study_intensity || 'medium'
    )

    // 4. Save to database for tracking
    // First ensure we have a plan_id (or create a simple one)
    let planId: string | null = null
    const { data: plan } = await supabase
      .from('study_plans')
      .select('id')
      .eq('user_id', user.id)
      .eq('status', 'active')
      .single()

    if (!plan) {
      // Auto-create a minimal plan
      const { data: newPlan } = await supabase
        .from('study_plans')
        .insert({
          user_id: user.id,
          level: profile.current_level,
          plan_data: { autoGenerated: true },
        })
        .select('id')
        .single()
      planId = newPlan?.id || null
    } else {
      planId = plan.id
    }

    if (planId) {
      const dbTasks = []
      for (const task of lesson.tasks) {
        const { data: dbTask, error } = await supabase.from('daily_tasks').insert({
          plan_id: planId,
          user_id: user.id,
          date: today,
          task_type: task.type,
          content: {
            ...task.content,
            unitId: progress.currentUnitId,  // track which unit this belongs to
          },
          duration_minutes: task.durationMinutes,
        }).select('id').single()

        if (error) console.error('Task insert error:', error)
        
        dbTasks.push({ ...task, id: dbTask?.id })
      }
      lesson.tasks = dbTasks
    }

    return NextResponse.json({
      lesson,
      unit: progress.currentUnit.titleEn,
      unitId: progress.currentUnitId,
      lessonsCompleted: progress.unitProgress.totalLessons,
      completedUnits: progress.completedUnits.length,
      focusAreas,
    })
  } catch (error: any) {
    console.error('Lesson generation error:', error)
    return NextResponse.json({ error: error.message || 'Failed to generate lesson' }, { status: 500 })
  }
}
